- name: SSH custom port testing
  wait_for: port={{custom_port}} timeout=5 host={{ansible_host}}
  register: custom_ssh_port
  delegate_to: "localhost"
  ignore_errors: true

- name: Set ansible_port to custom
  set_fact: ansible_port={{custom_port}}
  when: custom_ssh_port.state is defined and custom_ssh_port.state == "started"

- name: Set ansible_port to default when things not right
  set_fact: ansible_port=22
  when: custom_ssh_port.state is undefined
