- name: Try connecting with SSH custom port
  wait_for: port={{custom_port}} timeout=5 host={{ansible_host}}
  delegate_to: "localhost"
  register: customPortValue
  ignore_errors: true

- name: Set ansible_port to custom
  set_fact: ansible_port={{custom_port}}
  when: customPortValue.state is defined and customPortValue.state == "started"

- name: Change back to the default port when things not right
  set_fact: ansible_port=22
  when: customPortValue.state is undefined
