- name: Create the custom user with {{selected_groups}} group
  user: name={{username}} password={{password}} groups={{selected_groups}} shell=/bin/bash append=true
  register: userValue
  when: ansible_user == "root"

- block:
  - name: Create .ssh directory
    file: path=/home/{{username}}/.ssh state=directory mode="0700" owner={{username}} group={{username}}

  - name: Copy authorized_keys to new user
    copy: remote_src=true src=/root/.ssh/authorized_keys dest=/home/{{username}}/.ssh/authorized_keys mode="0600" owner={{username}} group={{username}}

  - name: Disable SSH root Login
    lineinfile: dest=/etc/ssh/sshd_config regexp="^{{item}}" line="{{item}} no"
    with_items:
        - PermitRootLogin
        - PasswordAuthentication
    notify: restart sshd

  - meta: flush_handlers

  - name: Set fact ansible_user to custom
    set_fact: ansible_user={{username}}

  when: userValue.changed == true
